name: Notify Slack on PR Review Request

on:
  pull_request:
    types: [review_requested]

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
    - name: Send notification to Slack
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      run: |
        REVIEWERS=$(jq '.requested_reviewers' "$GITHUB_EVENT_PATH")

        if [ $(echo "$REVIEWERS" | jq 'length') -gt 0 ]; then
            REVIEWER=$(echo "$REVIEWERS" | jq -r '.[0].login')
            USERS_LIST=$(curl -s -X GET "https://slack.com/api/users.list" -H "Authorization: Bearer $SLACK_TOKEN")
            REVIEWER_ID="<@$(echo "$USERS_LIST" | jq -r ".members[] | select(.profile.display_name == \"$REVIEWER\") | .id")>"
        else
            echo "No reviewers requested"
            exit 1
        fi

        PR_TITLE=$(jq -r '.pull_request.title' "$GITHUB_EVENT_PATH")
        PR_URL=$(jq -r '.pull_request.html_url' "$GITHUB_EVENT_PATH")

        curl -X POST -H 'Content-type: application/json' --data "{
          \"text\": \"$REVIEWER_ID 님에게 새로운 PR 리뷰 요청이 있습니다: *<$PR_URL|$PR_TITLE>*\"
        }" $SLACK_WEBHOOK_URL

