name: Notify Slack on PR Review Request

on:
  pull_request:
    types: [review_requested]

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
    - name: Send notification to Slack
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        # PR 제목과 URL 추출
        PR_TITLE=$(jq -r '.pull_request.title' "$GITHUB_EVENT_PATH")
        PR_URL=$(jq -r '.pull_request.html_url' "$GITHUB_EVENT_PATH")

        # PR의 브랜치명 추출
        BRANCH_NAME=$(jq -r '.pull_request.head.ref' "$GITHUB_EVENT_PATH")

        # Slack 알림 전송
        curl -X POST -H 'Content-type: application/json' --data "{
          \"text\": \"\`$BRANCH_NAME\`에서 새로운 PR이 있습니다: *<$PR_URL|$PR_TITLE>*\"
        }" $SLACK_WEBHOOK_URL
