name: Notify Slack on PR Review Request

on:
  pull_request:
    types: [review_requested]

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
    - name: Send notification to Slack
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      run: |
        REVIEWER=$(jq -r '.pull_request.requested_reviewers[0].login' "$GITHUB_EVENT_PATH")
        echo "Reviewer: $REVIEWER"
        REVIEWER_ID="<@$(curl -s -X GET "https://slack.com/api/users.list" -H "Authorization: Bearer $SLACK_TOKEN" | jq -r ".members[] | select(.profile.display_name == \"$REVIEWER\") | .id")>"
        echo "Reviewer ID: $REVIEWER_ID"
        PR_TITLE=$(jq -r '.pull_request.title' "$GITHUB_EVENT_PATH")
        PR_URL=$(jq -r '.pull_request.html_url' "$GITHUB_EVENT_PATH")

        curl -X POST -H 'Content-type: application/json' --data "{
          \"text\": \"$REVIEWER_ID 님에게 새로운 PR 리뷰 요청이 있습니다: *<$PR_URL|$PR_TITLE>*\"
        }" $SLACK_WEBHOOK_URL

